### ISSUE TITLE
Error when build job 

### ISSUE THREAD

**Issue by danjesus** [bartschuller/monorepo-experiments#1]
Hello,

I'm getting the error 
No item named monorepo-library found

Could you help me?

**Comment by danjesus** [comment]
@bartschuller could you help me?

**Comment by bartschuller** [comment]
These were just experiments and I don't have the Jenkins instance anymore in which I tested this. I think what I did was to create a build in jenkins for each of the 3 subprojects, in addition to the one for the project as a whole. For the subprojects, the builds need to point to the Jenkinsfile inside the appropriate subproject.

If I was going to really use this, it would have to be combined with an automated way to create the builds for the subprojects. This is possible, but I ultimately never switched to a monorepo, so I didn't pursue it further.
